- name: Install System Packages 1 (build-essential)
  apt:
    name: ["build-essential"]
  tags:
    - install
    - neovim
    - core
- name: Install System Packages 2 (the rest)
  apt: 
    pkg:
    - curl
    - htop
  tags:
    - install
    - core
