- name: Installing stow
  apt: name=stow
  tags:
    - install
    - dotfiles
- name: Cloning .dotfiles
  become_user: "{{ ansible_user }}" 
  ansible.builtin.git:
    repo: 'https://github.com/tsniemi/dotfiles.git'
    dest: "/home/{{ lookup('env', 'HOME') }}/dotfiles"
  tags:
    - install
    - dotfiles
- name: Stow dotfiles
  become_user: "{{ ansible_user }}"
  shell: cd /home/"{{ ansible_user }}"/dotfiles && make all
  tags:
    - install
    - dotfiles
